apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: book-ranker
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: a2lrbw==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: book-ranker
data:
  POSTGRES_DB: books

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: book-ranker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kristijan885/booker-spring-kiii:1.3
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/books
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          ports:
            - containerPort: 8080

