version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kiko
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kristijan885/booker-spring-kiii:latest
    platform: linux/amd64
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/books
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kiko
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
    command: --interval 20

volumes:
  postgres-data:

