apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: book-ranker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kristijan885/booker-spring-kiii:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://citus-coordinator:5432/books
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          ports:
            - containerPort: 8080

